BASE_URL = 'https://stellarburgers.nomoreparties.site/api/'
REG_USER_ENDPOINT = 'auth/register'
LOGIN_USER_ENDPOINT = 'auth/login'
GET_USER_ENDPOINT = 'auth/user'
ORDERS_ENDPOINT = 'orders'
INGREDIENTS_ENDPOINT = 'ingredients'
